# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'MyMoneyHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMoneyHelper

  pod 'R.swift'

  target 'MyMoneyHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMoneyHelperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
