# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'MyMoneyHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyMoneyHelper

  pod 'R.swift'
  pod 'RealmSwift'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'MyMoneyHelperTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

  target 'MyMoneyHelperUITests' do
    inherit! :search_paths
    # Pods for testing


  end

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
        end
    end
end
